import { GENERATED, type ProblemDefinition } from '../problem.js';

/**
 * Generated batch `gen-lc-032` (anchored to a public problem index; metadata only).
 *
 * Machine-drafted on 2026-09-16 and admitted only after
 * every reference solution passed every test on the judge
 * (`scripts/author-batch.ts`). Statements are original; provenance says so.
 */

const p = (d: ProblemDefinition): ProblemDefinition => d;

const base = { provenance: GENERATED } as const;

export const GEN_LC_032_PROBLEMS: ProblemDefinition[] = [
  p({
    ...base,
    slug: "count-misplaced-flags",
    difficulty: "EASY",
    tier: "TIER_1",
    patternFamily: "ARRAYS_HASHING",
    title: "Misplaced Flag Count",
    patternTags: ["arrays","counting","parity"],
    signatureId: "fn:ints->int",
    avgSolveSeconds: 600,
    promptMarkdown: "You are organizing a line of alternating colored flags represented by an integer array `flags`. A flag is considered correctly placed if its parity (even or odd) matches the parity of its index (0-indexed). That is, at index 0, the flag value should be even; at index 1, the flag value should be odd, and so on.\n\nDetermine the number of flags that are misplaced, meaning their parity does not match their index's parity.\n\n**Constraints**\n- `1 <= flags.length <= 1000`\n- `0 <= flags[i] <= 10000`\n\n**Example 1**\n```\ninput:\n4 7 2 5\noutput: 0\n```\nExplanation: Indices are 0 (even), 1 (odd), 2 (even), 3 (odd). Values are 4 (even), 7 (odd), 2 (even), 5 (odd). All match.\n\n**Example 2**\n```\ninput:\n1 2 3 4\noutput: 4\n```\nExplanation: All elements have the opposite parity of their indices.\n\n**Example 3**\n```\ninput:\n2 2 2\noutput: 1\n```\nExplanation: Only the element at index 1 is misplaced, as it is even but the index is odd.\n\n**Follow-up:** Can you solve this in \\(\\mathcal{O}(N)\\) time and \\(\\mathcal{O}(1)\\) space?",
    editorialMarkdown: "## Misplaced Flag Count\n\nTo solve this, iterate through the array, keeping track of the current index. For each element, check if `flags[i] % 2` is not equal to `i % 2`. Increment a counter each time they differ.\n\n**Complexity:**\n- **Time Complexity:** \\(\\mathcal{O}(N)\\) where \\(N\\) is the length of the array, since we examine each element once.\n- **Space Complexity:** \\(\\mathcal{O}(1)\\) as we only need a single counter variable.\n\n**Common Trap:**\nA common mistake is forgetting that `0` is an even number, or messing up the 0-based indexing checks.",
    referenceSolution: {
      JAVASCRIPT: "function solve(flags) {\n    let count = 0;\n    for (let i = 0; i < flags.length; i++) {\n        if ((flags[i] % 2) !== (i % 2)) count++;\n    }\n    return count;\n}",
      TYPESCRIPT: "function solve(flags: number[]): number {\n    let count = 0;\n    for (let i = 0; i < flags.length; i++) {\n        if ((flags[i] % 2) !== (i % 2)) count++;\n    }\n    return count;\n}",
      PYTHON: "def solve(flags):\n    return sum(1 for i, x in enumerate(flags) if (x % 2) != (i % 2))",
      JAVA: "    static int solve(int[] flags) {\n        int count = 0;\n        for (int i = 0; i < flags.length; i++) {\n            if ((flags[i] % 2) != (i % 2)) count++;\n        }\n        return count;\n    }",
      CPP: "int solve(vector<int> flags) {\n    int count = 0;\n    for (int i = 0; i < flags.size(); i++) {\n        if ((flags[i] % 2) != (i % 2)) count++;\n    }\n    return count;\n}",
      GO: "func solve(flags []int) int {\n    count := 0\n    for i, x := range flags {\n        if (x % 2) != (i % 2) {\n            count++\n        }\n    }\n    return count\n}",
    },
    tests: [
      { stdin: "4 7 2 5", expectedStdout: "0", isSample: true },
      { stdin: "1 2 3 4", expectedStdout: "4", isSample: true },
      { stdin: "2 2 2", expectedStdout: "1" },
      { stdin: "0", expectedStdout: "0" },
      { stdin: "1", expectedStdout: "1" },
      { stdin: "1 1 1 1 1 1", expectedStdout: "3" },
      { stdin: "100 200 300 400", expectedStdout: "2" },
      { stdin: "3 3 3 3", expectedStdout: "2" },
    ],
  }),

  p({
    ...base,
    slug: "count-valid-access-codes",
    difficulty: "EASY",
    tier: "TIER_1",
    patternFamily: "ARRAYS_HASHING",
    title: "Count Valid Access Codes",
    patternTags: ["strings","counting","conditionals"],
    signatureId: "fn:strings->int",
    avgSolveSeconds: 400,
    promptMarkdown: "You are verifying a list of security `codes` generated by a legacy system. An access code is considered valid if it meets two conditions:\n1. It has exactly 5 characters.\n2. It starts with the letter 'X'.\n\nGiven the array of `codes`, return the total number of valid access codes.\n\n**Constraints**\n- `1 <= codes.length <= 1000`\n- `1 <= codes[i].length <= 20`\n- `codes[i]` consists of alphanumeric characters.\n\n**Example 1**\n```\ninput:\nX1234 Y1234 XABCD X12\noutput: 2\n```\nExplanation: \"X1234\" and \"XABCD\" are valid because they have exactly 5 characters and start with 'X'. \"Y1234\" starts with 'Y', and \"X12\" has only 3 characters.\n\n**Example 2**\n```\ninput:\nXX XY XX123 XXXX\noutput: 1\n```\nExplanation: Only \"XX123\" has 5 characters and starts with 'X'.\n\n**Example 3**\n```\ninput:\n12345 abcde XXXXXX\noutput: 0\n```\nExplanation: None of the codes meet both conditions.\n\n**Follow-up:** Can you solve this in \\(\\mathcal{O}(N \\times L)\\) time, where \\(L\\) is the average string length?",
    editorialMarkdown: "## Count Valid Access Codes\n\nTo find the number of valid codes, we iterate through the list of strings and apply the conditions given in the problem description. We check if the length of the string is exactly 5 and if the first character is 'X'.\n\n**Complexity:**\n- **Time Complexity:** \\(\\mathcal{O}(N \\times L)\\) where \\(N\\) is the number of strings and \\(L\\) is the string length. String operations like getting length and first character are typically \\(\\mathcal{O}(1)\\) in many languages, making it effectively \\(\\mathcal{O}(N)\\).\n- **Space Complexity:** \\(\\mathcal{O}(1)\\) as we only keep a counter.\n\n**Common Trap:**\nA common trap is accessing the first character of an empty string without checking its length first (though the constraints guarantee length >= 1), or confusing exact matches with prefix matches.",
    referenceSolution: {
      JAVASCRIPT: "function solve(codes) {\n    let count = 0;\n    for (let s of codes) {\n        if (s.length === 5 && s[0] === 'X') count++;\n    }\n    return count;\n}",
      TYPESCRIPT: "function solve(codes: string[]): number {\n    let count = 0;\n    for (let s of codes) {\n        if (s.length === 5 && s[0] === 'X') count++;\n    }\n    return count;\n}",
      PYTHON: "def solve(codes):\n    return sum(1 for s in codes if len(s) == 5 and s[0] == 'X')",
      JAVA: "    static int solve(String[] codes) {\n        int count = 0;\n        for (String s : codes) {\n            if (s.length() == 5 && s.charAt(0) == 'X') count++;\n        }\n        return count;\n    }",
      CPP: "int solve(vector<string> codes) {\n    int count = 0;\n    for (const string& s : codes) {\n        if (s.length() == 5 && s[0] == 'X') count++;\n    }\n    return count;\n}",
      GO: "func solve(codes []string) int {\n    count := 0\n    for _, s := range codes {\n        if len(s) == 5 && s[0] == 'X' {\n            count++\n        }\n    }\n    return count\n}",
    },
    tests: [
      { stdin: "X1234 Y1234 XABCD X12", expectedStdout: "2", isSample: true },
      { stdin: "XX XY XX123 XXXX", expectedStdout: "1", isSample: true },
      { stdin: "12345 abcde XXXXXX", expectedStdout: "0" },
      { stdin: "X1234", expectedStdout: "1" },
      { stdin: "A", expectedStdout: "0" },
      { stdin: "X0000 X1111 X2222", expectedStdout: "3" },
      { stdin: "XXXXX XXXXX", expectedStdout: "2" },
      { stdin: "x1234 X1234", expectedStdout: "1" },
    ],
  }),

  p({
    ...base,
    slug: "count-primary-hubs",
    difficulty: "EASY",
    tier: "TIER_1",
    patternFamily: "BIT_MANIPULATION",
    title: "Primary Network Hubs",
    patternTags: ["bit-manipulation","counting","power-of-two"],
    signatureId: "fn:int->int",
    avgSolveSeconds: 450,
    promptMarkdown: "A telecommunications network assigns its devices unique IDs ranging from 1 to `limit`. A device acts as a \"primary hub\" if its ID is a power of 2 (meaning its binary representation contains exactly one '1' bit).\n\nDetermine the total number of primary hubs in the network.\n\n**Constraints**\n- `1 <= limit <= 10^9`\n\n**Example 1**\n```\ninput:\n10\noutput: 4\n```\nExplanation: The IDs in the range [1, 10] that are powers of 2 are 1, 2, 4, and 8.\n\n**Example 2**\n```\ninput:\n16\noutput: 5\n```\nExplanation: The IDs are 1, 2, 4, 8, and 16.\n\n**Example 3**\n```\ninput:\n1\noutput: 1\n```\nExplanation: The only ID is 1, which is a power of 2 (2^0).\n\n**Follow-up:** Can you solve this in \\(\\mathcal{O}(\\log N)\\) time or even \\(\\mathcal{O}(1)\\) time?",
    editorialMarkdown: "## Primary Network Hubs\n\nWe need to find how many powers of 2 are less than or equal to `limit`. This is equivalent to finding the position of the most significant bit of `limit`. A simple way is to start with 1 and keep multiplying by 2 (or shifting left) until it exceeds `limit`, counting how many such numbers we find.\n\n**Complexity:**\n- **Time Complexity:** \\(\\mathcal{O}(\\log N)\\) because we iterate over the bits of `limit`. Many languages offer built-in bit length operations that do this in \\(\\mathcal{O}(1)\\).\n- **Space Complexity:** \\(\\mathcal{O}(1)\\) as we only use a few variables.\n\n**Common Trap:**\nA common mistake is using floating-point operations like `log2(limit)` which can introduce precision errors for large integers, or forgetting that `1` is a power of 2.",
    referenceSolution: {
      JAVASCRIPT: "function solve(limit) {\n    let count = 0;\n    let current = 1;\n    while (current <= limit) {\n        count++;\n        current *= 2;\n    }\n    return count;\n}",
      TYPESCRIPT: "function solve(limit: number): number {\n    let count = 0;\n    let current = 1;\n    while (current <= limit) {\n        count++;\n        current *= 2;\n    }\n    return count;\n}",
      PYTHON: "def solve(limit):\n    count = 0\n    current = 1\n    while current <= limit:\n        count += 1\n        current *= 2\n    return count",
      JAVA: "    static int solve(int limit) {\n        int count = 0;\n        long current = 1;\n        while (current <= limit) {\n            count++;\n            current *= 2;\n        }\n        return count;\n    }",
      CPP: "int solve(int limit) {\n    int count = 0;\n    long long current = 1;\n    while (current <= limit) {\n        count++;\n        current *= 2;\n    }\n    return count;\n}",
      GO: "func solve(limit int) int {\n    count := 0\n    current := int64(1)\n    for current <= int64(limit) {\n        count++\n        current *= 2\n    }\n    return count\n}",
    },
    tests: [
      { stdin: "10", expectedStdout: "4", isSample: true },
      { stdin: "16", expectedStdout: "5", isSample: true },
      { stdin: "1", expectedStdout: "1" },
      { stdin: "2", expectedStdout: "2" },
      { stdin: "3", expectedStdout: "2" },
      { stdin: "1000", expectedStdout: "10" },
      { stdin: "1000000000", expectedStdout: "30" },
      { stdin: "1023", expectedStdout: "10" },
    ],
  }),

  p({
    ...base,
    slug: "count-single-shift-servers",
    difficulty: "EASY",
    tier: "TIER_1",
    patternFamily: "ARRAYS_HASHING",
    title: "Single Shift Servers",
    patternTags: ["arrays","counting","hash-map"],
    signatureId: "fn:ints->int",
    avgSolveSeconds: 750,
    promptMarkdown: "You are analyzing the activity logs of multiple servers. An array `logs` contains the IDs of servers that were active during consecutive minutes. A server is considered to have worked a \"single shift\" if all of its active minutes occur in one contiguous block, meaning there are no gaps where the server was inactive and then became active again.\n\nCount how many unique servers worked exactly a single shift.\n\n**Constraints**\n- `1 <= logs.length <= 1000`\n- `1 <= logs[i] <= 1000`\n\n**Example 1**\n```\ninput:\n1 1 2 2 1\noutput: 1\n```\nExplanation: Server 1 is active at minutes 0, 1, and 4 (not a single contiguous block). Server 2 is active at minutes 2 and 3 (a single contiguous block). So only 1 server worked a single shift.\n\n**Example 2**\n```\ninput:\n4 5 5 6\noutput: 3\n```\nExplanation: Servers 4, 5, and 6 all appear in single contiguous blocks.\n\n**Example 3**\n```\ninput:\n7 7 7\noutput: 1\n```\nExplanation: Server 7 is active in one block.\n\n**Follow-up:** Can you solve this in \\(\\mathcal{O}(N)\\) time and \\(\\mathcal{O}(U)\\) space, where \\(U\\) is the number of unique servers?",
    editorialMarkdown: "## Single Shift Servers\n\nWe need to verify if all occurrences of each server ID are consecutive. We can do this by keeping track of the previously seen elements. If we encounter a server ID that we have seen before, but the immediate preceding minute belonged to a different server, then the server has multiple shifts.\n\n**Complexity:**\n- **Time Complexity:** \\(\\mathcal{O}(N)\\) where \\(N\\) is the number of elements in the logs, as we process each element once.\n- **Space Complexity:** \\(\\mathcal{O}(U)\\) where \\(U\\) is the number of unique servers, needed to store their presence in a set or map.\n\n**Common Trap:**\nA common mistake is forgetting to count single occurrences as valid \"single shifts\" or failing to record that a server was already encountered.",
    referenceSolution: {
      JAVASCRIPT: "function solve(logs) {\n    let seen = new Set();\n    let invalid = new Set();\n    let prev = -1;\n    for (let x of logs) {\n        if (x !== prev) {\n            if (seen.has(x)) {\n                invalid.add(x);\n            }\n            seen.add(x);\n            prev = x;\n        }\n    }\n    return seen.size - invalid.size;\n}",
      TYPESCRIPT: "function solve(logs: number[]): number {\n    let seen = new Set<number>();\n    let invalid = new Set<number>();\n    let prev = -1;\n    for (let x of logs) {\n        if (x !== prev) {\n            if (seen.has(x)) {\n                invalid.add(x);\n            }\n            seen.add(x);\n            prev = x;\n        }\n    }\n    return seen.size - invalid.size;\n}",
      PYTHON: "def solve(logs):\n    seen = set()\n    invalid = set()\n    prev = -1\n    for x in logs:\n        if x != prev:\n            if x in seen:\n                invalid.add(x)\n            seen.add(x)\n            prev = x\n    return len(seen) - len(invalid)",
      JAVA: "    static int solve(int[] logs) {\n        java.util.Set<Integer> seen = new java.util.HashSet<>();\n        java.util.Set<Integer> invalid = new java.util.HashSet<>();\n        int prev = -1;\n        for (int x : logs) {\n            if (x != prev) {\n                if (seen.contains(x)) {\n                    invalid.add(x);\n                }\n                seen.add(x);\n                prev = x;\n            }\n        }\n        return seen.size() - invalid.size();\n    }",
      CPP: "int solve(vector<int> logs) {\n    unordered_set<int> seen;\n    unordered_set<int> invalid;\n    int prev = -1;\n    for (int x : logs) {\n        if (x != prev) {\n            if (seen.count(x)) {\n                invalid.insert(x);\n            }\n            seen.insert(x);\n            prev = x;\n        }\n    }\n    return seen.size() - invalid.size();\n}",
      GO: "func solve(logs []int) int {\n    seen := make(map[int]bool)\n    invalid := make(map[int]bool)\n    prev := -1\n    for _, x := range logs {\n        if x != prev {\n            if seen[x] {\n                invalid[x] = true\n            }\n            seen[x] = true\n            prev = x\n        }\n    }\n    return len(seen) - len(invalid)\n}",
    },
    tests: [
      { stdin: "1 1 2 2 1", expectedStdout: "1", isSample: true },
      { stdin: "4 5 5 6", expectedStdout: "3", isSample: true },
      { stdin: "7 7 7", expectedStdout: "1" },
      { stdin: "1", expectedStdout: "1" },
      { stdin: "1 2 1 2", expectedStdout: "0" },
      { stdin: "2 1 3 4 5", expectedStdout: "5" },
      { stdin: "1 2 3 3 2 1", expectedStdout: "1" },
      { stdin: "100 100 200 100", expectedStdout: "1" },
    ],
  }),

  p({
    ...base,
    slug: "count-passing-serial-numbers",
    difficulty: "EASY",
    tier: "TIER_1",
    patternFamily: "MATH_GEOMETRY",
    title: "Quality Control Serial Numbers",
    patternTags: ["counting","digits","math"],
    signatureId: "fn:int->int",
    avgSolveSeconds: 450,
    promptMarkdown: "A factory produces items with consecutive serial numbers starting from 1 up to a given integer `limit`. An item passes the initial quality control check if the sum of the digits in its serial number is an even number.\n\nCount the total number of items that pass this check.\n\n**Constraints**\n- `1 <= limit <= 1000`\n\n**Example 1**\n```\ninput:\n10\noutput: 4\n```\nExplanation: The numbers with even digit sums are 2, 4, 6, and 8. The number 10 has a digit sum of 1+0=1 (odd).\n\n**Example 2**\n```\ninput:\n20\noutput: 10\n```\nExplanation: The passing numbers are 2, 4, 6, 8, 11, 13, 15, 17, 19, and 20. There are 10 in total.\n\n**Example 3**\n```\ninput:\n1\noutput: 0\n```\nExplanation: The only number is 1, whose sum of digits is odd.\n\n**Follow-up:** Can you solve this in \\(\\mathcal{O}(N \\log_{10} N)\\) time or better?",
    editorialMarkdown: "## Quality Control Serial Numbers\n\nThe most straightforward approach is to iterate through all numbers from 1 to `limit`. For each number, calculate the sum of its digits, and if the sum is even, increment the count.\n\n**Complexity:**\n- **Time Complexity:** \\(\\mathcal{O}(N \\log_{10} N)\\) because we iterate \\(N\\) times and summing the digits takes time proportional to the number of digits.\n- **Space Complexity:** \\(\\mathcal{O}(1)\\) as only a few variables are needed for counting and digit extraction.\n\n**Common Trap:**\nA common mistake is missing the number itself if doing string conversions incorrectly, or over-complicating the math instead of just simulating the process for small limits.",
    referenceSolution: {
      JAVASCRIPT: "function solve(limit) {\n    let count = 0;\n    for (let i = 1; i <= limit; i++) {\n        let sum = 0;\n        let temp = i;\n        while (temp > 0) {\n            sum += temp % 10;\n            temp = Math.floor(temp / 10);\n        }\n        if (sum % 2 === 0) count++;\n    }\n    return count;\n}",
      TYPESCRIPT: "function solve(limit: number): number {\n    let count = 0;\n    for (let i = 1; i <= limit; i++) {\n        let sum = 0;\n        let temp = i;\n        while (temp > 0) {\n            sum += temp % 10;\n            temp = Math.floor(temp / 10);\n        }\n        if (sum % 2 === 0) count++;\n    }\n    return count;\n}",
      PYTHON: "def solve(limit):\n    count = 0\n    for i in range(1, limit + 1):\n        if sum(int(d) for d in str(i)) % 2 == 0:\n            count += 1\n    return count",
      JAVA: "    static int solve(int limit) {\n        int count = 0;\n        for (int i = 1; i <= limit; i++) {\n            int sum = 0;\n            int temp = i;\n            while (temp > 0) {\n                sum += temp % 10;\n                temp /= 10;\n            }\n            if (sum % 2 == 0) count++;\n        }\n        return count;\n    }",
      CPP: "int solve(int limit) {\n    int count = 0;\n    for (int i = 1; i <= limit; i++) {\n        int sum = 0;\n        int temp = i;\n        while (temp > 0) {\n            sum += temp % 10;\n            temp /= 10;\n        }\n        if (sum % 2 == 0) count++;\n    }\n    return count;\n}",
      GO: "func solve(limit int) int {\n    count := 0\n    for i := 1; i <= limit; i++ {\n        sum := 0\n        temp := i\n        for temp > 0 {\n            sum += temp % 10\n            temp /= 10\n        }\n        if sum % 2 == 0 {\n            count++\n        }\n    }\n    return count\n}",
    },
    tests: [
      { stdin: "10", expectedStdout: "4", isSample: true },
      { stdin: "20", expectedStdout: "10", isSample: true },
      { stdin: "1", expectedStdout: "0" },
      { stdin: "30", expectedStdout: "14" },
      { stdin: "100", expectedStdout: "49" },
      { stdin: "500", expectedStdout: "249" },
      { stdin: "999", expectedStdout: "499" },
      { stdin: "1000", expectedStdout: "499" },
    ],
  }),
];
