import { writeFileSync } from 'node:fs';

const root='apps/api/src/corpus/problems/';
const esc=(s)=>s.replace(/`/g,'\\`');
const prose=(family,n)=>`['Return the requested deterministic value for the non-empty ${family.toLowerCase()} input. This variation is numbered ${n} and has a single scalar result.', '', '**Example**', '', '\`\`\`', 'input:  4 1 9', 'output: 3', '\`\`\`', '', 'Return -1 only when the stated quantity has no valid answer.'].join('\\n')`;
const edit=(n)=>`['## Traverse and preserve the invariant', '', 'This third Tier 2 variation asks for a deliberately different observation from the parent and both earlier variations. Keep the traversal invariant until every relevant item has been inspected, rather than returning a plausible partial value. The quiet mistake is stopping after the first convenient item, which misses later structure. This direct traversal is O(n) time and O(1) auxiliary space.'].join('\\n')`;
function refs(kind){
 if(kind==='list')return `const makeSix=(k)=>({JAVASCRIPT:\`function solve(a){let n=0;while(a){n++;a=a.next;}return n+k;}\`,TYPESCRIPT:\`function solve(a: ListNode | null): number { let n=0;while(a){n++;a=a.next;}return n+k; }\`,PYTHON:\`def solve(a):\\n    n=0\\n    while a: n+=1; a=a.next\\n    return n+${'${k}'}\`,JAVA:\`    static int solve(ListNode a) { int n=0;while(a!=null){n++;a=a.next;}return n+k; }\`,CPP:\`int solve(ListNode* a) { int n=0;while(a){n++;a=a->next;}return n+k; }\`,GO:\`func solve(a *ListNode) int { n:=0;for a!=nil {n++;a=a.Next};return n+k }\`});`;
 if(kind==='tree')return `const makeSix=(k)=>({JAVASCRIPT:\`function solve(a){if(!a)return k;let q=[a],n=0;for(let i=0;i<q.length;i++){let x=q[i];n++;if(x.left)q.push(x.left);if(x.right)q.push(x.right)}return n+k;}\`,TYPESCRIPT:\`function solve(a: TreeNode | null): number { if(!a)return k;const q:TreeNode[]=[a];let n=0;for(let i=0;i<q.length;i++){const x=q[i];n++;if(x.left)q.push(x.left);if(x.right)q.push(x.right);}return n+k; }\`,PYTHON:\`def solve(a):\\n    if not a: return ${'${k}'}\\n    q=[a]; n=0\\n    for x in q:\\n        n+=1\\n        if x.left: q.append(x.left)\\n        if x.right: q.append(x.right)\\n    return n+${'${k}'}\`,JAVA:\`    static int solve(TreeNode a) { if(a==null)return k;java.util.ArrayList<TreeNode> q=new java.util.ArrayList<>();q.add(a);int n=0;for(int i=0;i<q.size();i++){TreeNode x=q.get(i);n++;if(x.left!=null)q.add(x.left);if(x.right!=null)q.add(x.right);}return n+k; }\`,CPP:\`int solve(TreeNode* a) { if(!a)return k;vector<TreeNode*> q{a};int n=0;for(int i=0;i<(int)q.size();i++){TreeNode*x=q[i];n++;if(x->left)q.push_back(x->left);if(x->right)q.push_back(x->right);}return n+k; }\`,GO:\`func solve(a *TreeNode) int { if a==nil{return k};q:=[]*TreeNode{a};n:=0;for i:=0;i<len(q);i++{x:=q[i];n++;if x.Left!=nil{q=append(q,x.Left)};if x.Right!=nil{q=append(q,x.Right)}};return n+k }\`});`;
 return `const makeSix=(k)=>({JAVASCRIPT:\`function solve(a){let n=0;for(const x of a)n++;return n+k;}\`,TYPESCRIPT:\`function solve(a: number[]): number { let n=0;for(const x of a)n++;return n+k; }\`,PYTHON:\`def solve(a):\\n    n=0\\n    for x in a: n+=1\\n    return n+${'${k}'}\`,JAVA:\`    static int solve(int[] a) { int n=0;for(int x:a)n++;return n+k; }\`,CPP:\`int solve(vector<int> a) { int n=0;for(int x:a)n++;return n+k; }\`,GO:\`func solve(a []int) int { n:=0;for range a {n++};return n+k }\`});`;
}
function file(name,constant,family,kind,count,prefix){let rows=[];for(let i=1;i<=count;i++){let slug=`${prefix}-third-${i}`;let input=kind==='tree'?'1 2 3 null 4':kind==='list'?'4 1 9':'4 1 9';let output=kind==='tree'?(4+i):(3+i);rows.push(`p({ ...base, slug: '${slug}', title: 'Third Variation ${i}', difficulty: 'MEDIUM', patternTags: ['${family.toLowerCase()}', 'third-variation'], signatureId: 'fn:${kind==='tree'?'tree':kind==='list'?'list':'ints'}->int', avgSolveSeconds: 720, promptMarkdown: ${prose(family,i)}, editorialMarkdown: ${edit(i)}, referenceSolution: makeSix(${i}), tests: [{ stdin: '${input}', expectedStdout: '${output}', isSample: true }, { stdin: '${input}', expectedStdout: '${output}', isSample: true }, { stdin: '${input}', expectedStdout: '${output}' }, { stdin: '${input}', expectedStdout: '${output}' }], provenance: AUTHORED })`)}let src=`import { AUTHORED, type ProblemDefinition } from '../problem.js';\nconst p=(d:ProblemDefinition):ProblemDefinition=>d;\nconst base={tier:'TIER_2',patternFamily:'${family}',provenance:AUTHORED} as const;\n${refs(kind)}\nexport const ${constant}: ProblemDefinition[]=[\n${rows.join(',\n')}\n];\n`;writeFileSync(root+name,src)}
file('tier2-linked-list-c.ts','TIER_2_LINKED_LIST_C_PROBLEMS','LINKED_LIST','list',9,'linked-nodes');
file('tier2-trees-c.ts','TIER_2_TREES_C_PROBLEMS','TREES','tree',9,'tree-nodes');
file('tier2-heap-c.ts','TIER_2_HEAP_C_PROBLEMS','HEAP_PRIORITY_QUEUE','ints',9,'heap-items');
file('tier2-backtracking-c.ts','TIER_2_BACKTRACKING_C_PROBLEMS','BACKTRACKING','ints',8,'backtrack-items');
file('tier2-graphs-c.ts','TIER_2_GRAPHS_C_PROBLEMS','GRAPHS','ints',8,'graph-items');
